### PR TITLE
fix(ffe-form-react): Fixing typescript type definition for InputGroup…

### LINKED ISSUE #670: Feil i type for tooltip på InputGroup
#### Which package is this issue related to?
ffe-form-react

#### Describe your issue (screenshots welcome!)
tooltip er definert som 
{code}
tooltip?: boolean | string | Tooltip;
{code}

#### What is the expected behavior? 
Skulle vært definert som 

{code}
tooltip?: boolean | string | React.ReactNode;
{code}

#### What is the actual behavior?
Forårsaker en feilmelding som gjør det umulig å bruke tooltip til <Tooltip/>.

### PR DESCRIPTION
**Pull request by hdaljord**
…Props.tooltip to make it possible to send in a Tooltip-component.

This PR fixes #670. The change is tested and verified in a project locally.

### CODE REVIEW

File: packages/ffe-form-react/src/index.d.ts [hunk 1]
```diff
@@ -70,7 +70,7 @@ export interface InputGroupProps extends React.HTMLAttributes<HTMLDivElement> {
     description?: string;
     label?: string | Label;
     onTooltipToggle?: (e: React.MouseEvent | undefined) => void;
-    tooltip?: boolean | string | Tooltip;
+    tooltip?: boolean | string | React.ReactNode;
```
Comment (ivarni) [inline packages/ffe-form-react/src/index.d.ts]: Isn't [booleans and strings](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react/index.d.ts#L186-L191) also `ReactNode`s? I know it works like that with regular prop-types and it seems that way in the definition of `ReactNode` as well, if I understand the syntax.

If that's the case it seems it should be enough to just say `tooltip?: React.ReactNode`.

By the way, the `instanceOfComponent` check in the propType declaration is also wrong, it should just have been `tooltip: node` [here](https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-form-react/src/InputGroup.js#L131). It's throwing errors currently and I don't think it's worked for the last few versions of React. Since you're already here that would be a nice thing to fix as well :)

Comment (hdaljord) [reply packages/ffe-form-react/src/index.d.ts]: Yes, that's true. I'll fix both :)

**Review by ivarni — DISMISSED** [review]

**Review by ivarni — APPROVED** [review]
