### PR TITLE
fix(ffe-account-selector-react): Suggestions will now correctly lose …

### LINKED ISSUE #435: AccountSelectorMulti won't close when focus is moved to another element
#### Which package is this issue related to?
ffe-account-selector-react

#### Describe your issue (screenshots welcome!)
When opening the account selector using the button on the right, the account selector won't close when focus is moved to another element in the page.
image

#### What is the expected behavior? 
The account-selector should close when focus is moved to another element in the page.

#### What is the actual behavior?
The account-selector stays open even though focus is moved to a different element.

#### Steps to reproduce
- Click the button/arrow to open the account selector and see that the list of accounts is opened and the textfield does not have focus
- Click outside the account selector and notice that the list of accounts is still open even though focus is not in the account selector

### PR DESCRIPTION
**Pull request by simjes**
…focus

The suggestion list will now close when AccountSelector lose focus after opening it by clicking the chevron

Fixes #435

### CODE REVIEW

File: packages/ffe-account-selector-react/src/subcomponents/input-field/InputField.js [hunk 1]
```diff
@@ -40,9 +40,14 @@ class Input extends Component {
         this.props.onReset();
     }
 
-    onExpandOrCollapse(e) {
+    onExpandOrCollapse(e, isSuggestionsShowing) {
```
Comment (selbekk) [inline packages/ffe-account-selector-react/src/subcomponents/input-field/InputField.js]: Can you get this value from `this.props.isSuggestionsShowing` instead of passing it as an argument?

**Review by selbekk — CHANGES_REQUESTED** [review]
Great job on this PR - especially with adding tests and what not.

I would love for the callback to refer to `this.props` instead of passing the value as an argument to the event handler - but that's the only change I can think of. Good stuff!

**Comment by simjes** [comment]
@selbekk Updated :)

**Review by selbekk — APPROVED** [review]

**Comment by selbekk** [comment]
So can you please explain to me why you're doing this instead of what we did previously? I'm not well enough versed with this code to understand its implications.

**Review by antidecaf — APPROVED** [review]

**Comment by simjes** [comment]
e.preventDefault() will prevent focus being set on an element so the onBlur() would not fire when clicking outside the inputField component.
Instead I put focus on the input element when you click the button. Setting focus on the button itself would also work, but there would be a border on the button and I didn’t want to change the style.

I can’t remember what it was, but there was another issue with putting focus on the button.

**Comment by selbekk** [comment]
Thanks for the explanation @simjes :+1: and thank you for your first contribution!
