### PR TITLE
fix(ffe-icons-react): Don't set inline size on SVG

### LINKED ISSUE #285: React icons are having height/width props set on them
#### Which package is this issue related to?

`ffe-icons-react`

#### Describe your issue (screenshots welcome!)

When using icons from the `ffe-icons-react` package they all come with the `height` and `width` property set.

#### What is the expected behavior? 

I'm expecting us to rely on the FFE components setting only the viewbox, leaving the consumer in charge of controlling the actual size of the icon

#### What is the actual behavior?

During the generation of React components, the size-props are set:
https://github.com/SpareBank1/designsystem/blob/develop/packages/ffe-icons-react/src/build-jsx-components.js#L38-L39

In certain cases this forces me to override those sizes using the `style` prop (which will win over these props) but I shouldn't have to be doing that.

### PR DESCRIPTION
**Pull request by ivarni**
No longer adds `width={150} height={150} to the generated SVGs.
This should not affect you, as both inline styling AND CSS will
override those props. The only case where it seems to matter is
if you're embedding an `ffe-icons-react` SVG inside another SVG.

Fixes #285

### CODE REVIEW

File: packages/ffe-icons-react/src/build-jsx-components.js [hunk 1]
```diff
@@ -28,21 +36,18 @@ const createSvgMap = () => {
...
-        xmlMode: true
+        xmlMode: true,
     });
     const svg = $('svg');
     // React does not support namespace definitions
     svg.attr('xmlns', null);
     svg.attr('xmlns:svg', null);
 
-    svg.attr('height', 150);
-    svg.attr('width', 150);
```
Comment (ivarni) [inline packages/ffe-icons-react/src/build-jsx-components.js:39]: Looks like the commit-hook went over the formatting, but the only real change is the removal of these lines.

**Review by wkillerud — APPROVED** [review]
